### ISSUE TITLE
live login issue

### ISSUE THREAD

**Issue by talha468** [Lamelos/django-allauth-office365#2]
Hey, 

I am having trouble while login with live account. it gives error : 1048, "Column 'email' cannot be null"). Any help will be appreciated.

Thanks

**Comment by Lamelos** [comment]
Could you post the relevant settings you used?

**Comment by Lamelos** [comment]
Perhaps you need to use the Windows Live provider for Allauth: see https://django-allauth.readthedocs.io/en/latest/providers.html#windows-live

This provider is for Office365 which is different than Windows Live.
